### ISSUE TITLE
are you kidding me?

### ISSUE THREAD

**Issue by Coolieoka** [MoreAgentsIsAllYouNeed/More-Agents-Is-All-You-Need#2]
python merge_human_eval.py

**Comment by Coolieoka** [comment]
ModuleNotFoundError: No module named 'sacrebleu'
/Users/mac/.pyenv/versions/3.11.4/bin/python: can't open file '/Users/mac/Documents/CODE/multiagent/More-Agents-Is-All-You-Need/src/merge_human_eval.py': [Errno 2] No such file or directory
mac@macs-MacBook-Air script % 


where should i find this .py??

**Comment by MoreAgentsIsAllYouNeed** [comment]
pip install sacrebleu
